In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('Bank Customer Churn Prediction.csv')

In [3]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.shape

(10000, 12)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  int64
 1   credit_score      10000 non-null  int64
 2   country           10000 non-null  str
 3   gender            10000 non-null  str
 4   age               10000 non-null  int64
 5   tenure            10000 non-null  int64
 6   balance           10000 non-null  float64
 7   products_number   10000 non-null  int64
 8   credit_card       10000 non-null  int64
 9   active_member     10000 non-null  int64
 10  estimated_salary  10000 non-null  float64
 11  churn             10000 non-null  int64
dtypes: float64(2), int64(8), str(2)
memory usage: 1.0 MB

In [4]:
df.isnull().sum()

customer_id         0
credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [7]:
df.describe()

,customer_id,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,churn_label
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained

In [18]:
# label categorical columns
#for churn
df['churn_label'] = df['churn'].map({0:'Retained',
                      1 : 'Churned'})
# for active member
df['credit_card_label'] = df['credit_card'].map({0 : 'No',
                      1 : 'Yes'})

# for active member
df['active_member_label'] = df['active_member'].map({ 0 : 'Inactive',
                        1 : 'Active'})

In [19]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,churn_label,credit_card_label,active_member_label
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned,Yes,Active
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained,No,Active
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned,Yes,Inactive
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained,No,Inactive
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained,Yes,Active

In [21]:
df['age'].unique()

array([42, 41, 39, 43, 44, 50, 29, 27, 31, 24, 34, 25, 35, 45, 58, 32, 38,
       46, 36, 33, 40, 51, 61, 49, 37, 19, 66, 56, 26, 21, 55, 75, 22, 30,
       28, 65, 48, 52, 57, 73, 47, 54, 72, 20, 67, 79, 62, 53, 80, 59, 68,
       23, 60, 70, 63, 64, 18, 82, 69, 74, 71, 76, 77, 88, 85, 84, 78, 81,
       92, 83])

In [23]:
df.rename(columns = {'estimated_salary' : 'salary',
                    'products_number' : 'num_products'}, inplace = True)

In [24]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,num_products,credit_card,active_member,salary,churn,churn_label,credit_card_label,active_member_label
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned,Yes,Active
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained,No,Active
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned,Yes,Inactive
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained,No,Inactive
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained,Yes,Active

In [26]:
df.drop(columns = 'customer_id', inplace = True)

In [27]:
df.head()

,credit_score,country,gender,age,tenure,balance,num_products,credit_card,active_member,salary,churn,churn_label,credit_card_label,active_member_label
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned,Yes,Active
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained,No,Active
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned,Yes,Inactive
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained,No,Inactive
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained,Yes,Active

In [28]:
# create age and balance group
bins = [18,30,40,50,60,100]
labels = ['18-30','31-40','41-50','51-60','60+']
df['age_group'] = pd.cut(
    df['age'],
    bins = bins,
    labels = labels,
    right = True,
    include_lowest= True
)

In [29]:
df.head()

,credit_score,country,gender,age,tenure,balance,num_products,credit_card,active_member,salary,churn,churn_label,credit_card_label,active_member_label,age_group
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned,Yes,Active,41-50
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained,No,Active,41-50
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned,Yes,Inactive,41-50
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained,No,Inactive,31-40
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained,Yes,Active,41-50

In [31]:
df['balance_group'] = pd.cut(df['balance'],
                       bins = [-1,0,50000, 100000, 200000, 300000],
                       labels = ['Zero','Low','Medium','High','Very High'])

In [32]:
df.head()

,credit_score,country,gender,age,tenure,balance,num_products,credit_card,active_member,salary,churn,churn_label,credit_card_label,active_member_label,age_group,balance_group
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,Churned,Yes,Active,41-50,Zero
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained,No,Active,41-50,Medium
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,Churned,Yes,Inactive,41-50,High
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained,No,Inactive,31-40,Zero
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained,Yes,Active,41-50,High

In [36]:
df['credit_score_group'] = pd.cut(df['credit_score'], 
    bins=[300, 500, 650, 750, 850],
    labels=['Poor', 'Fair', 'Good', 'Excellent'])

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [37]:
df.dtypes

credit_score              int64
country                     str
gender                      str
age                       int64
tenure                    int64
balance                 float64
num_products              int64
credit_card               int64
active_member             int64
salary                  float64
churn                     int64
churn_label                 str
credit_card_label           str
active_member_label         str
age_group              category
balance_group          category
credit_score_group     category
dtype: object

In [38]:
df.to_csv('bank_churn_cleaned.csv', index=False)